### ISSUE TITLE
¿Qué es la dificultad de una vía?

### ISSUE THREAD

**Issue by giorgiogiovanni** [FabriConde/CLIMB-VR#10]
Es una valoración _pseudo-numérica_ que determina el grado de dificultad.
https://es.wikipedia.org/wiki/Graduaci%C3%B3n_de_dificultad

Se utiliza en general la escala francesa, aunque se suele utilizar en muchos casos la escala UUIA para los niveles bajos:
+ Niveles bajos: I-V
+ Niveles altos: numeros 6-9 donde cada nivel tiene 6 subniveles: a, a+, b, b+, c, c+

**Comment by giorgiogiovanni** [comment]
Existen diferentes escalas y cierta discrepancia entre ellas...
https://climbaround.com/curiosidades/grados-escalada/#:~:text=La%20dificultad%20m%C3%ADnima%20de%20escalada,6c%2B%2C%207a%2C%207a%2B%E2%80%A6
https://www.tocandocumbre.com/apuntes-detalle.asp?id=7

Al parecer la más extendida es la francesa, donde los niveles de dificultad van codificados con un número, una letra y (opcionalmente) un signo +.

**Comment by FabriConde** [comment]
Se usará la francesa
