### ISSUE TITLE
Elección del lenguaje de programación 

### ISSUE THREAD

**Issue by FabriConde** [FabriConde/CLIMB-VR#5]
En clase vimos los diferentes lenguajes de programación que nos recomendó el profesor y yo creo que la mejor opción es Go.

**Comment by FabriConde** [comment]
@giorgiogiovanni

**Comment by giorgiogiovanni** [comment]
De hecho... creo que ya lo tenias pre-elegido. Ya que estaba estipulado en [README](https://github.com/FabriConde/CLIMB-VR/blob/main/README.md)...
