### ISSUE TITLE
¿Qué es un Sector de escalada?

### ISSUE THREAD

**Issue by giorgiogiovanni** [FabriConde/CLIMB-VR#7]
De acuerdo con #2, un sector de escalada es un área donde realizar escalada.
- Un sector tiene asignado un nombre único que lo identifica.
- Tiene una ubicación (coordenadas GPS) que lo georeferencia.
- En algunos casos son necesarias una serie de indicaciones o recomendaciones para llegar al lugar.
- Se compone de una serie de _Vías de escalada_. 
- La cantidad de vías de las que se compone (da una idea de la dimensión del sector).
   - ¿Sería util tener numero de vias y por otro lado una dimension del sector cualitativa (pequeño/medio/grande/gigante)?

**Comment by FabriConde** [comment]
Para: La cantidad de vías de las que se compone (da una idea de la dimensión del sector). Yo creo que con el número total de las vías la gente ya se hace una idea de la dimensiones del sector.
