### ISSUE TITLE
¿Qué es una vía de escalada?

### ISSUE THREAD

**Issue by giorgiogiovanni** [FabriConde/CLIMB-VR#8]
De acuerdo con #2, Una vía es un _camino_ o _trayecto_ que el escalador recorre desde la base hasta la cima (o punto intermedio) de una pared que está escalando.
- _Pertenece a un sector ( #7 )_
- Tiene un nombre que la identifica
- Tiene un grado de dificultad asociado
- Tiene una longitud en metros
- Tiene alguna información extra útil de la misma
   - Tipo de roca
   - Un estilo de escalada predominante
   - Lista de información extra: paso clave, característica distintiva

**Comment by FabriConde** [comment]
Para: Tiene alguna información útil de la misma, es algo opcional, es una cadena de texto que se puede rellenar con cualquier información adicional. Este campo se puede quitar del modelado si hace falta, no es algo importante.
